name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Logs / Screenshots

